name: climkern
channels:
  - conda-forge
dependencies:
  - pip
  - esmpy
  - xarray
  - scipy
  - xesmf
  - cftime
  - pooch
  - tqdm
  - fsspec
  - aiohttp
  - h5netcdf
  - h5py
  - plac
  - netcdf4
