name: Deploy Sphinx documentation to Pages

on: push

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Create conda environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
          micromamba-version: '1.4.1'
          environment-file: ci/environment.yml
      - name: Install editable climkern
        run: |
          python -m pip install --no-deps -e .
      - id: deployment
        uses: sphinx-notes/pages@v3
        with:
          documentation_path: ./docs/source
